version: '3.8'

services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "3001:3001" 
    volumes:
      - ./BackEnd:/app 
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=60357309
      - DB_NAME=core_notes
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 60357309
      MYSQL_DATABASE: core_notes
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p60357309"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: # Volume para persistir os dados do MySQL